## Notebook d'exemple de Numpy

### - Charger numpy

In [1]:
import numpy as np

### 1) Toutes les méthodes d'initialisation
- initialiser un tableau rempli de zeros de 10 éléments

In [4]:
a = np.zeros(10)
print(a)
a[9]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


0.0

- Initialiser une matrice remplie de zeros !!! d'entiers !!! de dimensions 5,10

In [5]:
np.zeros((10,408,408,3),dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

- créer un tableau à partir d'une liste de 100 éléments contenant tout les entiers entre 1 et 100. On pourrait le faire directement avec numpy également.

In [9]:
arr = np.array([list(range(100))])
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

- initialiser une matrice de taille (2,2,3) de valeur constante 42

In [21]:
np.full((2,2,3),42)

array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

- initialiser une matrice non initialsée de taille 3,3.
empty() est plus rapide que zeros(), mais sans garantie sur les valeurs contenues

In [6]:
np.empty((3,3))

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 7.075e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

- initialiser une matrice identité de taille 4

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- créer un tableau avec 7 valeurs réparties équitablement entre 1 et 3.5. Méthode très utilisée pour les graphes, pour échantilloner à intervalle régulier et afficher ces points

In [28]:
np.linspace(1,3.5,7)

array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333, 3.5       ])

- créer un tableau de taille (2,2,3) de chaine de 4 caractère contenant "ynov" dans chaque case. La taille de chaque chaine doit forcément être la même.

In [8]:
a = np.full(3,"Ynov")
a[0] = "YNOVVVV"
a

array(['YNOV', 'Ynov', 'Ynov'], dtype='<U4')

conversion entre pandas dataframe et numpy array

In [199]:
import pandas as pd
df = pd.DataFrame([[1,2],[3,4]])
df

0  1
0  1  2
1  3  4

In [200]:
np.array(df)

array([[1, 2],
       [3, 4]], dtype=int64)

la premiere dimension encode les lignes :

In [201]:
np.array(df)[0]

array([1, 2], dtype=int64)

## 2) Charger et sauvegarder ses valeurs

- créer une variable avec un tableau de taille (1000,1000)

In [9]:
my_array = np.full((1000,1000),42)
my_array

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]])

- sauvegarder ce tableau

In [11]:
np.save('my_array',my_array)

- charger le tableau sauvegardé et vérifier qu'il est bien égal au précédent

In [12]:
my_loaded_array = np.load('my_array.npy')
my_loaded_array == my_array

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

- on peut aussi sauvegarder en format compressé. Volume moins important, mais plus long à lire comme necessite decompression. Utilisé pour archiver mais pas pour stocker des données que l'on va utiliser par la suite.

In [13]:
np.savez_compressed('my_array',my_array)

In [21]:
arr = np.zeros(3)
np.savez('my_arrays',my_tab=my_array, toto_2=arr)

In [22]:
arrays = np.load("my_arrays.npz")

In [23]:
arrays["toto_2"]
arrays["my_tab"]

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]])

## 3) Obtenir de l'information sur le contenu d'un tableau

- La taille

In [88]:
my_array.shape

(1000, 1000)

- le nombre d'element

In [90]:
my_array.size

1000000

- le type

In [91]:
my_array.dtype

dtype('int32')

On peut changer ce type, pour pouvoir encoder plus de valeurs, faire passer des flottants en entiers ou encore réduire la taille en mémoire d'un tableau.

In [97]:
my_array.astype(np.int16)

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]], dtype=int16)

## 4) Les opérations matricielles

In [74]:
a = np.array([[12,3,4],[0,0,-2]])
b = np.array([[11,2,3],[4,0,2]])
c = np.array([1,2,3])
d = np.array([2,3])

- addition, soustraction

In [25]:
a + b

array([[23,  5,  7],
       [ 4,  0,  0]])

In [102]:
a - b

array([[ 1,  1,  1],
       [-4,  0, -4]])

Attention au résultat si les tableaux n'ont pas la même dimension, cela ne va pas toujours lever des erreurs

In [29]:
a + d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [30]:
a + c

array([[13,  5,  7],
       [ 1,  2,  1]])

- multiplication et division

In [32]:
a

array([[12,  3,  4],
       [ 0,  0, -2]])

In [33]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [31]:
a*b

array([[132,   6,  12],
       [  0,   0,  -4]])

In [120]:
a/b

d:\projects\ynov\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1.09090909,  1.5       ,  1.33333333],
       [ 0.        ,         nan, -1.        ]])

In [34]:
a*c

array([[12,  6, 12],
       [ 0,  0, -6]])

- la transposée

In [29]:
a.T

array([[1, 3],
       [2, 4]])

- le produit matriciel

In [129]:
a.dot(c)

array([30, -6])

Dot d'un vecteur par lui même nous donne sa norme (longueur) au carré

In [130]:
c.dot(c)

14

On peut calculer l'angle entre deux vecteurs avec dot (et arcos)

In [158]:
import math
v1 = np.array((0,1))
v2 = np.array((1,0))
angle = math.acos(v1.dot(v2)/(np.sqrt(v1.dot(v1))+np.sqrt(v2.dot(v2)))) # angle en radian
print("Angle entre v1 et v2 : ",angle/np.pi*180, "degré") # converti en degré

Angle entre v1 et v2 :  90.0 degré


## 5) Comparaison et aggrégations de tableau

- Les comparaisons

In [40]:
a == 0

array([[False, False, False],
       [False, False, False]])

In [41]:
a

array([[12,  3,  4],
       [ 1,  1, -2]])

In [174]:
a == b

array([[False, False, False],
       [False,  True, False]])

In [175]:
a == a.copy()

array([[ True,  True,  True],
       [ True,  True,  True]])

In [30]:
a >= 3

array([[False, False],
       [ True,  True]])

Applications : remplacer par 0 les cases ou a est strictement superieur à b

In [33]:
a[a > b] = 0
a

array([[ 0,  0,  0],
       [ 0,  0, -2]])

Et l'égalité de tableau ?

In [183]:
np.array_equal(a,b)

False

In [184]:
np.array_equal(a,a.copy())

True

- Trier un tableau:

In [37]:
a = np.array([[3,2,1,1,2,4]])
a.sort()
a

array([[1, 1, 2, 2, 3, 4]])

- les aggrégations : sum, mean, median, min, max, std,...

In [213]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [40]:
b.mean()

array([7.5, 1. , 2.5])

In [186]:
b.sum()

22

In [190]:
b.max()

11

In [191]:
b.min()

0

In [192]:
b.std()

3.4960294939005054

- on peut préciser sur quels axes les appliquer

In [212]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [206]:
b.max(axis=1) # pour appliquer par ligne

array([11,  4])

In [211]:
b.max(axis=0) # pour appliquer par colonne

array([11,  2,  3])

In [219]:
b.sort(axis=1)
b

array([[ 2,  3, 11],
       [ 0,  2,  4]])

## 6) accéder aux éléments

In [43]:
b[0,1]

2

In [42]:
b[0][1]

2

In [44]:
b[1]

array([4, 0, 2])

In [48]:
b[b<3]

array([2, 0, 2])

- Slicing. C'est un moyen efficace pour manipuler, acceder et copier plusieurs elements comme il ne demande pas un acces aux elements un par un.

In [49]:
a  = np.eye(4)
a[0,2]=3
a

array([[1., 0., 3., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
a[-2:-1]

array([[0., 0., 1., 0.]])

In [66]:
a[1:3,1:3]

array([[1., 0.],
       [0., 1.]])

In [241]:
a[:,-1]

array([0., 0., 0., 1.])

In [242]:
a[::-1] # change l'ordre des lignes

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 3., 0.]])

In [47]:
a[:,::-1] # change l'ordre des colonnes

array([[0., 3., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [68]:
a

array([[1., 0., 3., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
a[1:3,1:3]= b # copie b entre les lignes d'index 2 et 3 et colonnes d'index 1 et plus
a

array([[1., 0., 3., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 7) Autres fonctions pratiques en datascience

- beaucoup de fonctions et utilitaires mathématiques sont présents dans numpy

In [250]:
np.pi

3.141592653589793

In [251]:
np.cos(a)

array([[ 0.54030231,  1.        , -0.9899925 ,  1.        ],
       [ 1.        ,  0.54030231,  1.        ,  1.        ],
       [ 1.        , -0.41614684, -0.9899925 ,  0.0044257 ],
       [ 1.        ,  1.        , -0.41614684, -0.65364362]])

In [252]:
np.sqrt(a)

array([[1.        , 0.        , 1.73205081, 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.41421356, 1.73205081, 3.31662479],
       [0.        , 0.        , 1.41421356, 2.        ]])

- changer la taille du tableau

In [70]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

- nan et inf values

In [75]:
typical_data = b/b
typical_data[0,2]=np.inf
typical_data[1,2]=None
typical_data

C:\Users\MAXIME~1.CAR\AppData\Local\Temp/ipykernel_8684/2140603542.py:1: RuntimeWarning: invalid value encountered in true_divide
  typical_data = b/b


array([[ 1.,  1., inf],
       [ 1., nan, nan]])

- Detecter et remplacer les nan

In [76]:
np.isnan(typical_data)

array([[False, False, False],
       [False,  True,  True]])

In [77]:
np.nan_to_num(typical_data,nan=-1)

array([[ 1.00000000e+000,  1.00000000e+000,  1.79769313e+308],
       [ 1.00000000e+000, -1.00000000e+000, -1.00000000e+000]])

- le cas des inf

In [ ]:
np.isnan(typical_data)

array([[False, False,  True],
       [False, False, False]])

In [78]:
np.isfinite(typical_data)

array([[ True,  True, False],
       [ True, False, False]])

- remplacer infs et nan par une valeur:

In [79]:
typical_data2 = typical_data.copy()
typical_data2[~np.isfinite(typical_data2)] = 0
typical_data2

array([[1., 1., 0.],
       [1., 0., 0.]])

- remplacer les inf par la valeur maximum non inf :

In [292]:
maximum = np.max(typical_data[np.isfinite(typical_data)])

In [293]:

typical_data[np.isinf(typical_data)] = maximum
typical_data

array([[ 1.,  1.,  1.],
       [nan,  1., nan]])