# Partie niveau 1

1) Chargez le csv distance_villes.csv, qui comme son nom l'indique contient la distance entre plusieurs villes françaises, puis stockez le dans un tableau numpy.
- ne pas charger les lignes inutiles est plus efficace que de les charger puis de les supprimer !
- ne pas stocker l'index dans une colonne si celui-ci est présent

In [121]:
import pandas as pd
import numpy as np

df = pd.read_csv('./distance_villes.csv', sep=',', index_col=0, skipfooter=3)
mat = df.to_numpy()
display(df)

C:\Users\BEP29\AppData\Local\Temp\ipykernel_18312\3712044404.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('./distance_villes.csv', sep=',', index_col=0, skipfooter=3)


Paris   Lyon    Nice  Nantes  Strasbourg  Montpellier  \
Distance (kilomètres)                                                          
Paris                    NaN  462.0   931.0   380.0       488.0        746.0   
Lyon                   462.0    NaN   472.0   681.0       494.0        302.0   
Nice                   930.0  471.0     NaN  1143.0       790.0        326.0   
Nantes                 380.0  682.0  1145.0     NaN       860.0        824.0   
Strasbourg             487.0  491.0   788.0   860.0         NaN        791.0   
Montpellier            746.0  303.0   327.0   823.0       791.0          NaN   
Lille                  217.0  690.0  1159.0   598.0       522.0        963.0   
Rennes                 347.0  718.0  1186.0   106.0       827.0        894.0   
Reims                  143.0  487.0   955.0   516.0       347.0        786.0   
Saint-Étienne          523.0   64.0   491.0   661.0       552.0        322.0   
Angers                 293.0  595.0  1062.0    88.0       773.0        770.0   
Grenoble               574.0  106.0   466.0   786.0       534.0        296.0   
Nîmes                  711.0  252.0   281.0   872.0       740.0         55.0   
Aix-en-Provence        757.0  298.0   178.0   970.0       786.0        153.0   
Brest                  590.0  971.0  1441.0   298.0      1070.0       1121.0   

                        Lille  Rennes  Reims  Saint-Étienne  Angers  Grenoble  \
Distance (kilomètres)                                                           
Paris                   219.0   348.0  143.0          522.0   293.0     575.0   
Lyon                    689.0   718.0  487.0           62.0   594.0     107.0   
Nice                   1157.0  1186.0  955.0          490.0  1062.0     465.0   
Nantes                  597.0   107.0  515.0          662.0    88.0     786.0   
Strasbourg              549.0   827.0  347.0          550.0   773.0     533.0   
Montpellier             963.0   895.0  787.0          322.0   771.0     297.0   
Lille                     NaN   572.0  199.0          749.0   511.0     803.0   
Rennes                  572.0     NaN  483.0          699.0   126.0     823.0   
Reims                   198.0   483.0    NaN          546.0   429.0     600.0   
Saint-Étienne           750.0   698.0  548.0            NaN   574.0     155.0   
Angers                  511.0   128.0  429.0          576.0     NaN     700.0   
Grenoble                801.0   823.0  599.0          155.0   699.0       NaN   
Nîmes                   938.0   949.0  736.0          271.0   825.0     246.0   
Aix-en-Provence         984.0  1013.0  781.0          317.0   889.0     291.0   
Brest                   760.0   241.0  725.0          952.0   378.0    1076.0   

                        Nîmes  Aix-en-Provence   Brest  
Distance (kilomètres)                                   
Paris                   710.0            759.0   589.0  
Lyon                    251.0            299.0   970.0  
Nice                    279.0            176.0  1440.0  
Nantes                  874.0            972.0   296.0  
Strasbourg              739.0            787.0  1069.0  
Montpellier              56.0            154.0  1120.0  
Lille                   938.0            986.0   759.0  
Rennes                  948.0           1013.0   241.0  
Reims                   735.0            783.0   725.0  
Saint-Étienne           271.0            319.0   950.0  
Angers                  824.0            890.0   377.0  
Grenoble                245.0            293.0  1075.0  
Nîmes                     NaN            108.0  1169.0  
Aix-en-Provence         106.0              NaN  1267.0  
Brest                  1171.0           1269.0     NaN

In [122]:
columns_to_skip = 'Distance (kilomètres)'
df_ct = list(pd.read_csv('./distance_villes.csv', sep=',', index_col=False, skipfooter=3, usecols=lambda x: x not in columns_to_skip))
display(df_ct)

C:\Users\BEP29\AppData\Local\Temp\ipykernel_18312\3690786101.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df_ct = list(pd.read_csv('./distance_villes.csv', sep=',', index_col=False, skipfooter=3, usecols=lambda x: x not in columns_to_skip))


['Paris',
 'Lyon',
 'Nice',
 'Nantes',
 'Strasbourg',
 'Montpellier',
 'Lille',
 'Rennes',
 'Reims',
 'Saint-Étienne',
 'Angers',
 'Grenoble',
 'Nîmes',
 'Aix-en-Provence',
 'Brest']

2) Remplacez les valeurs manquantes par une valeur cohérente

In [130]:
np.isnan(mat)
df.fillna(0)

Paris   Lyon    Nice  Nantes  Strasbourg  Montpellier  \
Distance (kilomètres)                                                          
Paris                    0.0  462.0   931.0   380.0       488.0        746.0   
Lyon                   462.0    0.0   472.0   681.0       494.0        302.0   
Nice                   930.0  471.0     0.0  1143.0       790.0        326.0   
Nantes                 380.0  682.0  1145.0     0.0       860.0        824.0   
Strasbourg             487.0  491.0   788.0   860.0         0.0        791.0   
Montpellier            746.0  303.0   327.0   823.0       791.0          0.0   
Lille                  217.0  690.0  1159.0   598.0       522.0        963.0   
Rennes                 347.0  718.0  1186.0   106.0       827.0        894.0   
Reims                  143.0  487.0   955.0   516.0       347.0        786.0   
Saint-Étienne          523.0   64.0   491.0   661.0       552.0        322.0   
Angers                 293.0  595.0  1062.0    88.0       773.0        770.0   
Grenoble               574.0  106.0   466.0   786.0       534.0        296.0   
Nîmes                  711.0  252.0   281.0   872.0       740.0         55.0   
Aix-en-Provence        757.0  298.0   178.0   970.0       786.0        153.0   
Brest                  590.0  971.0  1441.0   298.0      1070.0       1121.0   

                        Lille  Rennes  Reims  Saint-Étienne  Angers  Grenoble  \
Distance (kilomètres)                                                           
Paris                   219.0   348.0  143.0          522.0   293.0     575.0   
Lyon                    689.0   718.0  487.0           62.0   594.0     107.0   
Nice                   1157.0  1186.0  955.0          490.0  1062.0     465.0   
Nantes                  597.0   107.0  515.0          662.0    88.0     786.0   
Strasbourg              549.0   827.0  347.0          550.0   773.0     533.0   
Montpellier             963.0   895.0  787.0          322.0   771.0     297.0   
Lille                     0.0   572.0  199.0          749.0   511.0     803.0   
Rennes                  572.0     0.0  483.0          699.0   126.0     823.0   
Reims                   198.0   483.0    0.0          546.0   429.0     600.0   
Saint-Étienne           750.0   698.0  548.0            0.0   574.0     155.0   
Angers                  511.0   128.0  429.0          576.0     0.0     700.0   
Grenoble                801.0   823.0  599.0          155.0   699.0       0.0   
Nîmes                   938.0   949.0  736.0          271.0   825.0     246.0   
Aix-en-Provence         984.0  1013.0  781.0          317.0   889.0     291.0   
Brest                   760.0   241.0  725.0          952.0   378.0    1076.0   

                        Nîmes  Aix-en-Provence   Brest  
Distance (kilomètres)                                   
Paris                   710.0            759.0   589.0  
Lyon                    251.0            299.0   970.0  
Nice                    279.0            176.0  1440.0  
Nantes                  874.0            972.0   296.0  
Strasbourg              739.0            787.0  1069.0  
Montpellier              56.0            154.0  1120.0  
Lille                   938.0            986.0   759.0  
Rennes                  948.0           1013.0   241.0  
Reims                   735.0            783.0   725.0  
Saint-Étienne           271.0            319.0   950.0  
Angers                  824.0            890.0   377.0  
Grenoble                245.0            293.0  1075.0  
Nîmes                     0.0            108.0  1169.0  
Aix-en-Provence         106.0              0.0  1267.0  
Brest                  1171.0           1269.0     0.0

In [124]:
mat = np.where(np.isnan(mat), 0, mat)
mat = np.nan_to_num(mat)
mat

array([[   0.,  462.,  931.,  380.,  488.,  746.,  219.,  348.,  143.,
         522.,  293.,  575.,  710.,  759.,  589.],
       [ 462.,    0.,  472.,  681.,  494.,  302.,  689.,  718.,  487.,
          62.,  594.,  107.,  251.,  299.,  970.],
       [ 930.,  471.,    0., 1143.,  790.,  326., 1157., 1186.,  955.,
         490., 1062.,  465.,  279.,  176., 1440.],
       [ 380.,  682., 1145.,    0.,  860.,  824.,  597.,  107.,  515.,
         662.,   88.,  786.,  874.,  972.,  296.],
       [ 487.,  491.,  788.,  860.,    0.,  791.,  549.,  827.,  347.,
         550.,  773.,  533.,  739.,  787., 1069.],
       [ 746.,  303.,  327.,  823.,  791.,    0.,  963.,  895.,  787.,
         322.,  771.,  297.,   56.,  154., 1120.],
       [ 217.,  690., 1159.,  598.,  522.,  963.,    0.,  572.,  199.,
         749.,  511.,  803.,  938.,  986.,  759.],
       [ 347.,  718., 1186.,  106.,  827.,  894.,  572.,    0.,  483.,
         699.,  126.,  823.,  948., 1013.,  241.],
       [ 143.,  487.,  9

In [125]:
mxm = np.max(mat[np.isfinite(mat)])
mat[np.isinf(mat)] = mxm
mat

array([[   0.,  462.,  931.,  380.,  488.,  746.,  219.,  348.,  143.,
         522.,  293.,  575.,  710.,  759.,  589.],
       [ 462.,    0.,  472.,  681.,  494.,  302.,  689.,  718.,  487.,
          62.,  594.,  107.,  251.,  299.,  970.],
       [ 930.,  471.,    0., 1143.,  790.,  326., 1157., 1186.,  955.,
         490., 1062.,  465.,  279.,  176., 1440.],
       [ 380.,  682., 1145.,    0.,  860.,  824.,  597.,  107.,  515.,
         662.,   88.,  786.,  874.,  972.,  296.],
       [ 487.,  491.,  788.,  860.,    0.,  791.,  549.,  827.,  347.,
         550.,  773.,  533.,  739.,  787., 1069.],
       [ 746.,  303.,  327.,  823.,  791.,    0.,  963.,  895.,  787.,
         322.,  771.,  297.,   56.,  154., 1120.],
       [ 217.,  690., 1159.,  598.,  522.,  963.,    0.,  572.,  199.,
         749.,  511.,  803.,  938.,  986.,  759.],
       [ 347.,  718., 1186.,  106.,  827.,  894.,  572.,    0.,  483.,
         699.,  126.,  823.,  948., 1013.,  241.],
       [ 143.,  487.,  9

3) Quelle est la meilleure ville où habiter si on doit voyager régulièrement sur toutes les villes du jeu de donnée ? 
- utiliser numpy (et pas des boucles)
- on suppose que la meilleure est celle qui permet un temps de trajet moyen le plus court

In [126]:
ct = np.where(np.mean(mat, axis=0) == np.amin(np.mean(mat, axis=0)))
df_ct[ct[0][0]]

'Lyon'

4) Quelle est la meilleure ville avoir des trajets le plus court possible ? quel est alors le pire temps de trajet ?

In [127]:
dist_min = np.where(np.amax(mat, axis=0) == np.amin(np.amax(mat, axis=0)))
df_ct[dist_min[0][0]]

'Paris'

In [128]:
dist_min = np.where(np.average(mat, axis=0) == np.amax(np.average(mat, axis=0)))
df_ct[dist_min[0][0]]

'Brest'

5) Question bonus: Faites cette question en dernier si vous faites le niveau 2.
    
    Proposez un itinéraire rapide pour passer par toutes les villes. Vous pouvez le faire sur moins de villes pour commencer.

# Niveau 2

Certains dataset sont trop volumineux pour être stockés en mémoire.
- évaluer la taille en mémoire du dataframe pandas 
- évaluer la taille en mémoire de la matrice numpy (attention, sys.getsizeof ne fonctionne pas pour tous les objets python)
- pouvez vous faire en sorte que les distances tiennent moins de 500 bytes en mémoire ?

In [129]:
import sys

# Le code suivant suppose que df est votre dataframe et mat votre matrice numpy

print("Taille du dataframe en mémoire:",sys.getsizeof(df))
print("Taille de la matrice numpy en mémoire :",mat.itemsize*mat.size)

Taille du dataframe en mémoire: 2827
Taille de la matrice numpy en mémoire : 1800


In [132]:
mat2 = mat.astype(np.uint16)
mat2 = mat2 / 6
mat2 = mat2.astype(np.uint8)

print(mat2)

print("\nTaille du dataframe en mémoire:",sys.getsizeof(df))
print("Taille de la matrice numpy en mémoire :",mat2.itemsize*mat2.size)

[[  0  77 155  63  81 124  36  58  23  87  48  95 118 126  98]
 [ 77   0  78 113  82  50 114 119  81  10  99  17  41  49 161]
 [155  78   0 190 131  54 192 197 159  81 177  77  46  29 240]
 [ 63 113 190   0 143 137  99  17  85 110  14 131 145 162  49]
 [ 81  81 131 143   0 131  91 137  57  91 128  88 123 131 178]
 [124  50  54 137 131   0 160 149 131  53 128  49   9  25 186]
 [ 36 115 193  99  87 160   0  95  33 124  85 133 156 164 126]
 [ 57 119 197  17 137 149  95   0  80 116  21 137 158 168  40]
 [ 23  81 159  86  57 131  33  80   0  91  71 100 122 130 120]
 [ 87  10  81 110  92  53 125 116  91   0  95  25  45  53 158]
 [ 48  99 177  14 128 128  85  21  71  96   0 116 137 148  62]
 [ 95  17  77 131  89  49 133 137  99  25 116   0  40  48 179]
 [118  42  46 145 123   9 156 158 122  45 137  41   0  18 194]
 [126  49  29 161 131  25 164 168 130  52 148  48  17   0 211]
 [ 98 161 240  49 178 186 126  40 120 158  63 179 195 211   0]]

Taille du dataframe en mémoire: 2827
Taille de la mat

- Pouvez vous réduire davantage l'espace en mémoire en acceptant une perte de précision ?
Faites passer la taille en mémoire à moins de 250 bytes.

- Evaluer la perte de précision : quelles sont la perte moyenne et la perte maximale ?
- Vérifiez que ces valeurs sont bien cohérentes.

In [134]:
mat3 = mat2.astype(np.uint16)
mat3 = np.multiply(mat3, 6)
print(mat3)

[[   0  462  930  378  486  744  216  348  138  522  288  570  708  756
   588]
 [ 462    0  468  678  492  300  684  714  486   60  594  102  246  294
   966]
 [ 930  468    0 1140  786  324 1152 1182  954  486 1062  462  276  174
  1440]
 [ 378  678 1140    0  858  822  594  102  510  660   84  786  870  972
   294]
 [ 486  486  786  858    0  786  546  822  342  546  768  528  738  786
  1068]
 [ 744  300  324  822  786    0  960  894  786  318  768  294   54  150
  1116]
 [ 216  690 1158  594  522  960    0  570  198  744  510  798  936  984
   756]
 [ 342  714 1182  102  822  894  570    0  480  696  126  822  948 1008
   240]
 [ 138  486  954  516  342  786  198  480    0  546  426  600  732  780
   720]
 [ 522   60  486  660  552  318  750  696  546    0  570  150  270  318
   948]
 [ 288  594 1062   84  768  768  510  126  426  576    0  696  822  888
   372]
 [ 570  102  462  786  534  294  798  822  594  150  696    0  240  288
  1074]
 [ 708  252  276  870  738   54  936  94

In [135]:
mat4=mat-mat3
mat4.astype(int)

array([[0, 0, 1, 2, 2, 2, 3, 0, 5, 0, 5, 5, 2, 3, 1],
       [0, 0, 4, 3, 2, 2, 5, 4, 1, 2, 0, 5, 5, 5, 4],
       [0, 3, 0, 3, 4, 2, 5, 4, 1, 4, 0, 3, 3, 2, 0],
       [2, 4, 5, 0, 2, 2, 3, 5, 5, 2, 4, 0, 4, 0, 2],
       [1, 5, 2, 2, 0, 5, 3, 5, 5, 4, 5, 5, 1, 1, 1],
       [2, 3, 3, 1, 5, 0, 3, 1, 1, 4, 3, 3, 2, 4, 4],
       [1, 0, 1, 4, 0, 3, 0, 2, 1, 5, 1, 5, 2, 2, 3],
       [5, 4, 4, 4, 5, 0, 2, 0, 3, 3, 0, 1, 0, 5, 1],
       [5, 1, 1, 0, 5, 0, 0, 3, 0, 0, 3, 0, 3, 3, 5],
       [1, 4, 5, 1, 0, 4, 0, 2, 2, 0, 4, 5, 1, 1, 2],
       [5, 1, 0, 4, 5, 2, 1, 2, 3, 0, 0, 4, 2, 2, 5],
       [4, 4, 4, 0, 0, 2, 3, 1, 5, 5, 3, 0, 5, 5, 1],
       [3, 0, 5, 2, 2, 1, 2, 1, 4, 1, 3, 0, 0, 0, 5],
       [1, 4, 4, 4, 0, 3, 0, 5, 1, 5, 1, 3, 4, 0, 1],
       [2, 5, 1, 4, 2, 5, 4, 1, 5, 4, 0, 2, 1, 3, 0]])

In [136]:
mat4.mean()

2.4044444444444446

In [137]:
mat4.max()

5.0

- attention à ne pas faire la soustraction sur la matrice en uint, uint est unsigned et ne gere pas les valeurs négatives