In [7]:
import tensorflow as tf
import numpy

In [9]:
(data_to_use), (data_on_side) = tf.keras.datasets.mnist.load_data()

In [18]:
data_on_side[0].shape

(10000, 28, 28)

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data_to_use[0], data_to_use[1], test_size=0.20, random_state=42)

In [15]:
x_train.shape

(48000, 28, 28)

In [19]:
x_test.shape

(12000, 28, 28)

In [20]:
y_train.shape

(48000,)

In [21]:
y_test.shape

(12000,)

In [24]:
# normalisation

x_train_normalized = x_train.astype(float) / 255
x_test_normalized = x_test.astype(float) / 255

In [25]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [26]:
# making categories encoded out of labels

y_train = tf.keras.utils.to_categorical(y_train, 10)

In [27]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [28]:
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [29]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [31]:
from tensorflow.keras.models import Sequential

In [32]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

num_filters = 8
filter_size = 3
pool_size = 2

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

In [33]:
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 8)         80        
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 8)        0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 1352)              0         
                                                                 
 dense (Dense)               (None, 10)                13530     
                                                                 
Total params: 13,610
Trainable params: 13,610
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(
  x_train,
  y_train,
  epochs=5,
  batch_size=128,
  validation_data=(x_test, y_test)
)

Epoch 1/5
469/469 [==============================] - 20s 43ms/step - loss: 0.3340 - accuracy: 0.9533 - val_loss: 0.3393 - val_accuracy: 0.9501
Epoch 2/5
469/469 [==============================] - 14s 30ms/step - loss: 0.2258 - accuracy: 0.9610 - val_loss: 0.3109 - val_accuracy: 0.9534
Epoch 3/5
469/469 [==============================] - 21s 44ms/step - loss: 0.1841 - accuracy: 0.9642 - val_loss: 0.2811 - val_accuracy: 0.9554
Epoch 4/5
469/469 [==============================] - 19s 40ms/step - loss: 0.1583 - accuracy: 0.9661 - val_loss: 0.2887 - val_accuracy: 0.9521
Epoch 5/5
469/469 [==============================] - 16s 34ms/step - loss: 0.1372 - accuracy: 0.9689 - val_loss: 0.2800 - val_accuracy: 0.9542
